In [1]:
import pandas as pd
import numpy as np
print("Data Upload : ")
df=pd.read_csv("heart.csv")
data=pd.DataFrame(df)
print(data.shape)
print(data.info())

Data Upload : 
(303, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  303 non-null    int64  
 1   sex                  303 non-null    int64  
 2   chest_pain_type      303 non-null    int64  
 3   resting_bp           303 non-null    int64  
 4   cholestoral          303 non-null    int64  
 5   fasting_blood_sugar  303 non-null    int64  
 6   restecg              303 non-null    int64  
 7   max_hr               303 non-null    int64  
 8   exang                303 non-null    int64  
 9   oldpeak              303 non-null    float64
 10  slope                303 non-null    int64  
 11  num_major_vessels    303 non-null    int64  
 12  thal                 303 non-null    int64  
 13  target               303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB
None


In [2]:
print(data.isnull().sum())

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
dtype: int64


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
X=data.drop("target",axis=1)
y=data["target"]
print(X.shape)
print(y.shape)
print(X.columns)
print(y.name)

(303, 13)
(303,)
Index(['age', 'sex', 'chest_pain_type', 'resting_bp', 'cholestoral',
       'fasting_blood_sugar', 'restecg', 'max_hr', 'exang', 'oldpeak', 'slope',
       'num_major_vessels', 'thal'],
      dtype='object')
target


In [4]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.4,random_state=10)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(X_test.shape)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

print(X_train_scaled[:2])


(181, 13)
(122, 13)
(181,)
(122, 13)
[[-0.08212761  0.73960026  1.0511439   1.12964137 -0.36946395 -0.42779263
  -0.9553319   0.66978893 -0.71297499  0.49983681  0.9625225  -0.68370351
   1.23227307]
 [-0.30235126  0.73960026  2.04206601  1.24152377  0.82179553  2.33758117
   0.92417978  1.21063084 -0.71297499  0.16226046 -0.65059391 -0.68370351
   1.23227307]]


In [5]:
model1=LogisticRegression()
model2=KNeighborsClassifier(n_neighbors=5)
model3=svm.SVC(kernel="rbf",gamma="scale",C=10)
model4=svm.SVC(kernel="poly",gamma="scale",C=100)
model5=svm.SVC(kernel="linear",gamma="scale",C=1000)
print("All Models : ")
print(model1)
print(model2)
print(model3)
print(model4)
print(model5)

All Models : 
LogisticRegression()
KNeighborsClassifier()
SVC(C=10)
SVC(C=100, kernel='poly')
SVC(C=1000, kernel='linear')


In [6]:
print("Fitting,Predicting and Evaluating of Model 1 : ")
model1.fit(X_train_scaled,y_train)
y1=model1.predict(X_test_scaled)
print("Results of Model 1 : \n",y1)
print("--------------------------------------------\nEvaluation of Model 1 (Logistic Regression):\n--------------------------------------------")
Accuracy1=accuracy_score(y_test,y1)
Precision1=precision_score(y_test,y1)
Recall1=recall_score(y_test,y1)
f1_1=f1_score(y_test,y1)
print("Accuracy : ",Accuracy1)
print("Precision : ",Precision1)
print("Recall : ",Recall1)
print("F1 Score : "  ,f1_1)
cm1=confusion_matrix(y_test,y1)
print("Confusion Matrix : ")
print(cm1)

Fitting,Predicting and Evaluating of Model 1 : 
Results of Model 1 : 
 [0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1
 0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1
 0 1 0 1 1 1 1 0 1 1 0]
--------------------------------------------
Evaluation of Model 1 (Logistic Regression):
--------------------------------------------
Accuracy :  0.7786885245901639
Precision :  0.7051282051282052
Recall :  0.9322033898305084
F1 Score :  0.8029197080291971
Confusion Matrix : 
[[40 23]
 [ 4 55]]


In [7]:
print("Fitting,Predicting and Evaluating of Model 2 : ")
model2.fit(X_train_scaled,y_train)
y2=model2.predict(X_test_scaled)
print("Results of Model 2 : \n",y2)
print("--------------------------------------------\nEvaluation of Model 2 (KNeighborsClassifier):\n--------------------------------------------")
Accuracy2=accuracy_score(y_test,y2)
Precision2=precision_score(y_test,y2)
Recall2=recall_score(y_test,y2)
f1_2=f1_score(y_test,y2)
print("Accuracy : ",Accuracy2)
print("Precision : ",Precision2)
print("Recall : ",Recall2)
print("F1 Score : "  ,f1_2)
cm2=confusion_matrix(y_test,y2)
print("Confusion Matrix : ")
print(cm2)

Fitting,Predicting and Evaluating of Model 2 : 
Results of Model 2 : 
 [0 1 0 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1
 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0
 0 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1
 0 1 0 1 1 1 1 0 1 1 0]
--------------------------------------------
Evaluation of Model 2 (KNeighborsClassifier):
--------------------------------------------
Accuracy :  0.7786885245901639
Precision :  0.7105263157894737
Recall :  0.9152542372881356
F1 Score :  0.8
Confusion Matrix : 
[[41 22]
 [ 5 54]]


In [8]:
print("Fitting,Predicting and Evaluating of Model 2.1 : (KNN Hyperparameter Tuning) ")
param_grid={'n_neighbors':[1,3,5,7,9,11]}
grid_search=GridSearchCV(KNeighborsClassifier(),param_grid,cv=5)
grid_search.fit(X_train_scaled,y_train)
best_knn=grid_search.best_estimator_
print(best_knn)
y21=best_knn.predict(X_test_scaled)
print("Results of Tuned KNN : \n",y21)
print("Results of Model 2 : \n",y2)
print("--------------------------------------------\nEvaluation of Model 2.1 (KNeighborsClassifier):\n--------------------------------------------")
Accuracy21=accuracy_score(y_test,y21)
Precision21=precision_score(y_test,y21)
Recall21=recall_score(y_test,y21)
f1_21=f1_score(y_test,y21)
print("Accuracy : ",Accuracy21)
print("Precision : ",Precision21)
print("Recall : ",Recall21)
print("F1 Score : "  ,f1_21)
cm21=confusion_matrix(y_test,y21)
print("Confusion Matrix : ")
print(cm21)

Fitting,Predicting and Evaluating of Model 2.1 : (KNN Hyperparameter Tuning) 
KNeighborsClassifier(n_neighbors=9)
Results of Tuned KNN : 
 [0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0
 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1
 0 1 0 1 1 1 1 0 1 1 0]
Results of Model 2 : 
 [0 1 0 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1
 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0
 0 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1
 0 1 0 1 1 1 1 0 1 1 0]
--------------------------------------------
Evaluation of Model 2.1 (KNeighborsClassifier):
--------------------------------------------
Accuracy :  0.7622950819672131
Precision :  0.6875
Recall :  0.9322033898305084
F1 Score :  0.7913669064748201
Confusion Matrix : 
[[38 25]
 [ 4 55]]


In [9]:
print("Fitting,Predicting and Evaluating of Model 3 : ")
model3.fit(X_train_scaled,y_train)
y3=model3.predict(X_test_scaled)
print("Results of Model 3 : \n",y3)
print("----------------------------\nEvaluation of Model 3 (SVC):\n----------------------------")
Accuracy3=accuracy_score(y_test,y3)
Precision3=precision_score(y_test,y3)
Recall3=recall_score(y_test,y3)
f1_3=f1_score(y_test,y3)
print("Accuracy : ",Accuracy3)
print("Precision : ",Precision3)
print("Recall : ",Recall3)
print("F1 Score : "  ,f1_3)
cm3=confusion_matrix(y_test,y3)
print("Confusion Matrix : ")
print(cm3)

Fitting,Predicting and Evaluating of Model 3 : 
Results of Model 3 : 
 [0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1
 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1 1
 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0 1
 0 0 0 1 1 1 1 0 1 0 0]
----------------------------
Evaluation of Model 3 (SVC):
----------------------------
Accuracy :  0.7786885245901639
Precision :  0.7285714285714285
Recall :  0.864406779661017
F1 Score :  0.7906976744186046
Confusion Matrix : 
[[44 19]
 [ 8 51]]


In [10]:
print("Fitting,Predicting and Evaluating of Model 4 : ")
model4.fit(X_train_scaled,y_train)
y4=model4.predict(X_test_scaled)
print("Results of Model 4 : \n",y4)
print("-----------------------------------------------\nEvaluation of Model 4 (SVC kernel=poly, C=100):\n-----------------------------------------------")
Accuracy4=accuracy_score(y_test,y4)
Precision4=precision_score(y_test,y4)
Recall4=recall_score(y_test,y4)
f1_4=f1_score(y_test,y4)
print("Accuracy : ",Accuracy4)
print("Precision : ",Precision4)
print("Recall : ",Recall4)
print("F1 Score : "  ,f1_4)
cm4=confusion_matrix(y_test,y4)
print("Confusion Matrix : ")
print(cm4)

Fitting,Predicting and Evaluating of Model 4 : 
Results of Model 4 : 
 [0 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0 1 1
 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1
 0 1 0 0 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1
 0 1 0 1 1 1 1 0 1 0 0]
-----------------------------------------------
Evaluation of Model 4 (SVC kernel=poly, C=100):
-----------------------------------------------
Accuracy :  0.7213114754098361
Precision :  0.6666666666666666
Recall :  0.847457627118644
F1 Score :  0.746268656716418
Confusion Matrix : 
[[38 25]
 [ 9 50]]


In [11]:
print("Fitting,Predicting and Evaluating of Model 5 : ")
model5.fit(X_train_scaled,y_train)
y5=model4.predict(X_test_scaled)
print("Results of Model 5 : \n",y5)
print("-----------------------------------------------\nEvaluation of Model 5 (SVC kernel=poly, C=100):\n-----------------------------------------------")
Accuracy5=accuracy_score(y_test,y5)
Precision5=precision_score(y_test,y5)
Recall5=recall_score(y_test,y5)
f1_5=f1_score(y_test,y5)
print("Accuracy : ",Accuracy5)
print("Precision : ",Precision5)
print("Recall : ",Recall5)
print("F1 Score : "  ,f1_5)
cm5=confusion_matrix(y_test,y5)
print("Confusion Matrix : ")
print(cm5)

Fitting,Predicting and Evaluating of Model 5 : 
Results of Model 5 : 
 [0 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 0 1 1
 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1
 0 1 0 0 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1
 0 1 0 1 1 1 1 0 1 0 0]
-----------------------------------------------
Evaluation of Model 5 (SVC kernel=poly, C=100):
-----------------------------------------------
Accuracy :  0.7213114754098361
Precision :  0.6666666666666666
Recall :  0.847457627118644
F1 Score :  0.746268656716418
Confusion Matrix : 
[[38 25]
 [ 9 50]]


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

models = {
    "Logistic Regression": LogisticRegression(),
    "KNN (k=5)": KNeighborsClassifier(n_neighbors=5),
    "KNN (k=9)": KNeighborsClassifier(n_neighbors=9),
    "SVM-RBF": SVC(kernel="rbf", gamma="scale", C=100),
    "SVM-Polynomial": SVC(kernel="poly", gamma="scale", C=100),
    "SVM-Linear": SVC(kernel="linear", C=100)
}

results = []

for name, model in models.items():

    # Fitting
    model.fit(X_train_scaled, y_train)

    # Prediction
    y_pred = model.predict(X_test_scaled)

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)

    TN, FP, FN, TP = cm.ravel()

    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1,
        TN,
        FP,
        FN,
        TP
    ])

# Create comparison DataFrame
comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "TN",
        "FP",
        "FN",
        "TP"
    ]
)

print(comparison)

                 Model  Accuracy  Precision    Recall  F1 Score  TN  FP  FN  \
0  Logistic Regression  0.778689   0.705128  0.932203  0.802920  40  23   4   
1            KNN (k=5)  0.778689   0.710526  0.915254  0.800000  41  22   5   
2            KNN (k=9)  0.762295   0.687500  0.932203  0.791367  38  25   4   
3              SVM-RBF  0.770492   0.718310  0.864407  0.784615  43  20   8   
4       SVM-Polynomial  0.721311   0.666667  0.847458  0.746269  38  25   9   
5           SVM-Linear  0.786885   0.708861  0.949153  0.811594  40  23   3   

   TP  
0  55  
1  54  
2  55  
3  51  
4  50  
5  56  


In [13]:
print("For the dataset we used: SVM WITH LINEAR KERNEL WON TO CLASSIFY THE BEST")

For the dataset we used: SVM WITH LINEAR KERNEL WON TO CLASSIFY THE BEST


In [14]:
from sklearn.model_selection import cross_val_score

models = {
    "Logistic Regression": LogisticRegression(),
    "KNN (k=5)": KNeighborsClassifier(n_neighbors=5),
    "KNN (k=9)": KNeighborsClassifier(n_neighbors=9),
    "SVM-RBF": SVC(kernel="rbf", gamma="scale", C=100),
    "SVM-Polynomial": SVC(kernel="poly", gamma="scale", C=100),
    "SVM-Linear": SVC(kernel="linear", C=100)
}

for name, model in models.items():

    scores = cross_val_score(
        model,
        X_train_scaled,
        y_train,
        cv=5,
        scoring="accuracy"
    )

    print(name)
    print("CV Scores:", scores)
    print("Mean Accuracy:", scores.mean())
    print("Standard Deviation:", scores.std())
    print("--------------------------------||||")

Logistic Regression
CV Scores: [0.83783784 0.83333333 0.88888889 0.88888889 0.72222222]
Mean Accuracy: 0.8342342342342342
Standard Deviation: 0.060884728737481277
--------------------------------||||
KNN (k=5)
CV Scores: [0.78378378 0.83333333 0.94444444 0.83333333 0.77777778]
Mean Accuracy: 0.8345345345345347
Standard Deviation: 0.059799736127121035
--------------------------------||||
KNN (k=9)
CV Scores: [0.86486486 0.91666667 0.88888889 0.86111111 0.77777778]
Mean Accuracy: 0.8618618618618619
Standard Deviation: 0.046505358120538146
--------------------------------||||
SVM-RBF
CV Scores: [0.75675676 0.75       0.75       0.80555556 0.72222222]
Mean Accuracy: 0.756906906906907
Standard Deviation: 0.027074532823761207
--------------------------------||||
SVM-Polynomial
CV Scores: [0.7027027  0.80555556 0.83333333 0.86111111 0.75      ]
Mean Accuracy: 0.7905405405405406
Standard Deviation: 0.05726412560217683
--------------------------------||||
SVM-Linear
CV Scores: [0.83783784 0.777

Accuracy: 1.0
