In [19]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
df=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
data=pd.DataFrame(df)
print(data)

    0   1
0   1   2
1   3   4
2   5   6
3   7   8
4   9  10
5  11  12


In [53]:
import warnings
warnings.filterwarnings("ignore")

from sklearn.cluster import KMeans
import numpy as np
import pandas as pd
kmeans=KMeans(n_clusters=3,random_state=42,n_init=10)
kmeans.fit(data)
labels=kmeans.labels_
print(labels)
centroids=kmeans.cluster_centers_
print(centroids)

[0 0 2 2 1 1]
[[ 2.  3.]
 [10. 11.]
 [ 6.  7.]]


In [55]:
kmeans2=KMeans(n_clusters=4,random_state=42,n_init=10)
kmeans2.fit(data)
labels2=kmeans2.labels_
centroids2=kmeans2.cluster_centers_
print(labels2)
print(centroids2)

[0 0 3 1 2 2]
[[ 2.  3.]
 [ 7.  8.]
 [10. 11.]
 [ 5.  6.]]
